### ISSUE TITLE
Páginas individuais de projetos.

### ISSUE THREAD

**Issue by VPortoV** [omateocortez/S2_ProjetoIntegrador_FrontEnd#10]
## A página deve conter:

- Título
- Descrição
- Data
- Imagens ( **se o projeto tiver mais que uma, deve ser colocado um carrossel invés de uma img** )

**Comment by VPortoV** [comment]
O código está pronto, só precisa ser embelezado.

commit df1335b

**Comment by omateocortez** [comment]
eu achei que tá legal, vejam e qualquer coisa reabram essa issue
