### ISSUE TITLE
Ajuste Menu

### ISSUE THREAD

**Issue by HenriqueNalin** [omateocortez/S2_ProjetoIntegrador_FrontEnd#16]
- [ ] Ajustar menu com a nova logo da ONG ( Os protótipos já estão todos com a logo nova, porém são prints então a qualidade está ruim. Cliente ainda não desponibilizou a logo adaptado para nossa identidade visual ).
- [x] Ajustar o nome das pages no menu para CAPSLOCK.

**Comment by omateocortez** [comment]
Não tem logo nova, mas mudei o caps na navbar
