### ISSUE TITLE
Tela de gerenciamento de funcionários

### ISSUE THREAD

**Issue by omateocortez** [omateocortez/S2_ProjetoIntegrador_FrontEnd#17]

**Comment by VPortoV** [comment]
Só falta colocar:
- [x] modal de editar user
- [x] embelezar tudo

**Comment by VPortoV** [comment]
fechei sm querer kkk
ops..

**Comment by omateocortez** [comment]
Falta poder **filtrar por funcionario ou membro**, o resto foi a maior parte, só back de fazer o botao de editar poder editar de fato

**Comment by VPortoV** [comment]
commit cbbf253
