### ISSUE TITLE
Acessibilidade & Legislação

### ISSUE THREAD

**Issue by VPortoV** [omateocortez/S2_ProjetoIntegrador_FrontEnd#26]
### Acessibilidade:
- [ ] Imagens devem possuir 'alt'
- [x] Elementos devem possuir atributos "aria" como por exemplo "aria-label" em botões.
- [x] Idealmente, a página deve ser legível em até 200% do tamanho original. (acho q já está mas só p/ garantir coloquei aqui).
- [ ] ~~Suporte para controle apenas via teclado.~~ (não obrigatório).
- [x] Adicionar 'title' aos hrefs (Não precisa ser todos; Evitar palavras como 'Clique', optar por 'Acesse').
#### Dica:
Testar o site usando [WAVE(Web Accessibility Evaluation Tool)](https://wave.webaim.org/).

### Legislação:
- [x] Fazer Termos de Uso.
- [x] Adicionar checkbox no cadastro, algo como: 'li e aceito os termos de uso e a politica de privacidade'.

**Comment by omateocortez** [comment]
tem até UserWay agora, tamos bem
