### ISSUE TITLE
Tirar imagem de crianças

### ISSUE THREAD

**Issue by VPortoV** [omateocortez/S2_ProjetoIntegrador_FrontEnd#27]
N pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode **Imagem está na página _'Quem Somos'_**  n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode

**Comment by omateocortez** [comment]
isso que é foda, alguma outra imagem pra por? porque imagem de crianca  n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode Imagem está na página 'Quem Somos' n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode

**Comment by omateocortez** [comment]
resolvi, porque imagem de crianca n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode Imagem está na página 'Quem Somos' n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode n pode
