### ISSUE TITLE
Tela 'Sua Conta'

### ISSUE THREAD

**Issue by VPortoV** [omateocortez/S2_ProjetoIntegrador_FrontEnd#39]
- [x] Botão para deletar conta;
- [x] Campos para editar NOME, SOBRENOME E EMAIL;
- [x] Botão para alterar senha;
- [x] Botão para salvar alterações;
- [x] Modal de confirmação, quando for para salvar as alterações. (Pede pra colocar senha antiga);
- [x] Modal de confirmação, quando for para apagar a conta. ('TEM CERTEZA QUE DESEJA EXCLUIR?');

**Comment by omateocortez** [comment]
A gente já tem as rotas é isso? ou tá marcado como feito por engano

**Comment by VPortoV** [comment]
Tudo integradinho :D

commit 64b19d1
