### ISSUE TITLE
Arrumar subtítulos 'Quem Somos'

### ISSUE THREAD

**Issue by VPortoV** [omateocortez/S2_ProjetoIntegrador_FrontEnd#41]
Feedback negativo das pessoas que viram o site.

**Comment by omateocortez** [comment]
po alguma ideia? o maluco do design me mandou isso kkkkkkkkk tô zoando

**Comment by VPortoV** [comment]
@malucododesign

**Comment by HenriqueNalin** [comment]
Na verdade os textos ja vieram prontos da ONG, só copiei e colei nos protótipos!

**Comment by VPortoV** [comment]
@HenriqueNalin desculpa se n ficou claro, tamo falando do visual, n do conteúdo dos textos.

**Comment by HenriqueNalin** [comment]
@VPortoV Mas tem que arrumar o conteúdo dos textos também, a gente não precisa escrever os títulos em Camel Case, não é java, não tem necessidade de escrever "Mãos Na Massa : Uma História De Não Sei O Que Não Sei Que Lá Fulano Ciclano"
