### ISSUE TITLE
Colocar 'ultima atualização' nos termos de uso

### ISSUE THREAD

**Issue by VPortoV** [omateocortez/S2_ProjetoIntegrador_FrontEnd#45]
Ta sem data kkkkkk
![imagem demonstrando o bug](https://github.com/user-attachments/assets/80606c51-4b1b-4260-a8be-6226a8e3ffb5)

**Comment by HenriqueNalin** [comment]
Eu esqueci de colocar, a data certa é 26/11/2024.

**Comment by VPortoV** [comment]
commit 337d8a0
