### ISSUE TITLE
Colocar a logo da ONG certa

### ISSUE THREAD

**Issue by HenriqueNalin** [omateocortez/S2_ProjetoIntegrador_FrontEnd#48]
Para de ser rebelde @omateocortez!

**Comment by omateocortez** [comment]
> Para de ser rebelde @omateocortez!

Ele n mandaram a Logo .png branca novaaaaa

**Comment by HenriqueNalin** [comment]
Usa a mesma que você tava usando antes, a qualidade dela estava boa!
